### PR TITLE
Default cookie face custom face

### PR DESCRIPTION
**Pull request by tusharhero**
redoing #10

### CODE REVIEW

**Comment by tusharhero** [comment]
Hurray! its finally rebased properly.

**Comment by tusharhero** [comment]
Its actuallly rebased properly...

**Comment by tusharhero** [comment]
hey @gsingh93, I think the PR is ready, I have added the user option as you said, I have also tested it on my computer. I have also rebased branch on to the main branch of this repository.

**Comment by gsingh93** [comment]
Thanks, looks good! Could you please make sure that the code is properly formatted? Hitting `TAB` on each changed line should work, or you can use something like [aphelia-mode](https://github.com/radian-software/apheleia), which is what I use. Once that's done, I'll go ahead and merge this.

**Pull request merged**
